package main

// These are all of the "official" tables
// Nice to have to check for anything following
// convention, but again--nothing is enforced.

// An example are the nefarious "Z" segments

type ControlTable map[ID]struct{}

func (table ControlTable) Valid(v ID) bool {
	_, ok := table[v]
	return ok
}

var UniversalIdTypes = ControlTable{
	"DNS":    {},
	"GUID":   {},
	"HCD":    {},
	"HL7":    {},
	"ISO":    {},
	"L":      {},
	"M":      {},
	"N":      {},
	"Random": {},
	"UUID":   {},
	"x400":   {},
	"x500":   {},
}

// All of the different HL7 message types
var MessageType = ControlTable{
	"ACK": {},
	"ADR": {},
	"ADT": {},
	"ARD": {},
	"BAR": {},
	"CNQ": {},
	"CSU": {},
	"DFT": {},
	"DSR": {},
	"EDR": {},
	"ERP": {},
	"EQQ": {},
	"MCF": {},
	"MDM": {},
	"MFD": {},
	"MFK": {},
	"MFN": {},
	"MFQ": {},
	"MFR": {},
	"ORF": {},
	"ORM": {},
	"ORR": {},
	"ORU": {},
	"OSQ": {},
	"OSR": {},
	"PEX": {},
	"PGL": {},
	"PGQ": {},
	"PPG": {},
	"PPP": {},
	"PPR": {},
	"PPT": {},
	"PPV": {},
	"PRR": {},
	"PTR": {},
	"PTV": {},
	"QRY": {},
	"RAR": {},
	"RAS": {},
	"RCI": {},
	"RCL": {},
	"RDE": {},
	"RDR": {},
	"RDS": {},
	"REF": {},
	"RER": {},
	"RGR": {},
	"RGV": {},
	"ROC": {},
	"ROD": {},
	"ROR": {},
	"RPA": {},
	"RPI": {},
	"RPL": {},
	"RPR": {},
	"RQA": {},
	"RQC": {},
	"RQI": {},
	"RRA": {},
	"RRD": {},
	"RRE": {},
	"RRG": {},
	"RRI": {},
	"SIU": {},
	"SPQ": {},
	"SQM": {},
	"SQR": {},
	"SRM": {},
	"SRR": {},
	"SUR": {},
	"TBR": {},
	"UDM": {},
	"VQQ": {},
	"VXQ": {},
	"VXR": {},
	"VXU": {},
	"VXX": {},
}

// Event (aka Trigger) Events
// there might be other found in the wild
var EventType = ControlTable{
	"022": {},
	"A01": {},
	"A02": {},
	"A03": {},
	"A04": {},
	"A05": {},
	"A06": {},
	"A07": {},
	"A08": {},
	"A09": {},
	"A10": {},
	"A11": {},
	"A12": {},
	"A13": {},
	"A14": {},
	"A15": {},
	"A16": {},
	"A17": {},
	"A18": {},
	"A19": {},
	"A20": {},
	"A21": {},
	"A22": {},
	"A23": {},
	"A24": {},
	"A25": {},
	"A26": {},
	"A27": {},
	"A28": {},
	"A29": {},
	"A30": {},
	"A31": {},
	"A32": {},
	"A33": {},
	"A34": {},
	"A35": {},
	"A36": {},
	"A37": {},
	"A38": {},
	"A39": {},
	"A40": {},
	"A41": {},
	"A42": {},
	"A43": {},
	"A44": {},
	"A45": {},
	"A46": {},
	"A47": {},
	"A48": {},
	"A49": {},
	"A50": {},
	"A51": {},
	"C01": {},
	"C02": {},
	"C03": {},
	"C04": {},
	"C05": {},
	"C06": {},
	"C07": {},
	"C08": {},
	"C09": {},
	"C10": {},
	"C11": {},
	"C12": {},
	"CNQ": {},
	"I01": {},
	"I02": {},
	"I03": {},
	"I04": {},
	"I05": {},
	"I06": {},
	"I07": {},
	"I08": {},
	"I09": {},
	"I10": {},
	"I11": {},
	"I12": {},
	"I13": {},
	"I14": {},
	"I15": {},
	"M01": {},
	"M02": {},
	"M03": {},
	"M04": {},
	"M05": {},
	"M06": {},
	"M07": {},
	"M08": {},
	"M09": {},
	"M10": {},
	"M11": {},
	"O01": {},
	"O02": {},
	"P01": {},
	"P02": {},
	"P03": {},
	"P04": {},
	"P05": {},
	"P06": {},
	"Q01": {},
	"Q02": {},
	"Q03": {},
	"Q04": {},
	"Q05": {},
	"Q06": {},
	"R01": {},
	"R02": {},
	"R03": {},
	"R04": {},
	"R05": {},
	"R06": {},
	"RAR": {},
	"RER": {},
	"ROR": {},
	"S01": {},
	"S02": {},
	"S03": {},
	"S04": {},
	"S05": {},
	"S06": {},
	"S07": {},
	"S08": {},
	"S09": {},
	"S10": {},
	"S11": {},
	"S12": {},
	"S13": {},
	"S14": {},
	"S15": {},
	"S16": {},
	"S17": {},
	"S18": {},
	"S19": {},
	"S20": {},
	"S21": {},
	"S22": {},
	"S23": {},
	"S24": {},
	"S25": {},
	"S26": {},
	"T01": {},
	"T02": {},
	"T03": {},
	"T04": {},
	"T05": {},
	"T06": {},
	"T07": {},
	"T09": {},
	"V01": {},
	"V02": {},
	"V03": {},
	"V04": {},
	"W01": {},
	"W02": {},
}

var SegmentTypes = ControlTable{
	"ACC": {},
	"ADD": {},
	"AID": {},
	"AIL": {},
	"AIP": {},
	"AIS": {},
	"AL1": {},
	"APR": {},
	"ARQ": {},
	"AUT": {},
	"BHS": {},
	"BLG": {},
	"BS":  {},
	"CDM": {},
	"CM0": {},
	"CM1": {},
	"CM2": {},
	"CSP": {},
	"CSR": {},
	"CSS": {},
	"CTD": {},
	"CTI": {},
	"DG1": {},
	"DRG": {},
	"DSC": {},
	"DSP": {},
	"EQL": {},
	"ERQ": {},
	"ERR": {},
	"EVN": {},
	"FAC": {},
	"FHS": {},
	"FT1": {},
	"FTS": {},
	"GT1": {},
	"IN1": {},
	"IN2": {},
	"IN3": {},
	"LCC": {},
	"LCH": {},
	"LDP": {},
	"LOC": {},
	"LRL": {},
	"MFA": {},
	"MFE": {},
	"MFI": {},
	"MRG": {},
	"MSA": {},
	"MSH": {},
	"NK1": {},
	"NPU": {},
	"NTE": {},
	"OBR": {},
	"OBX": {},
	"ODS": {},
	"ODT": {},
	"OM1": {},
	"OM2": {},
	"OM3": {},
	"OM4": {},
	"OM5": {},
	"OM6": {},
	"ORC": {},
	"PCR": {},
	"PD1": {},
	"PDC": {},
	"PEO": {},
	"PES": {},
	"PID": {},
	"PR1": {},
	"PRA": {},
	"PRC": {},
	"PRD": {},
	"PSR": {},
	"PV1": {},
	"PV2": {},
	"QAK": {},
	"QRD": {},
	"QRF": {},
	"RDF": {},
	"RDT": {},
	"RF1": {},
	"RQ1": {},
	"RQD": {},
	"RXA": {},
	"RXC": {},
	"RXD": {},
	"RXE": {},
	"RXG": {},
	"RXO": {},
	"RXR": {},
	"SCH": {},
	"STF": {},
	"SPR": {},
	"TXA": {},
	"UB1": {},
	"UB2": {},
	"URD": {},
	"URS": {},
	"VTQ": {},
}

var VersionIds = ControlTable{
	"2.0":   {},
	"2.0D":  {},
	"2.1":   {},
	"2.2":   {},
	"2.3":   {},
	"2.3.1": {},
	"2.4":   {},
	"2.5":   {},
	"2.6":   {},
	"2.7":   {},
	"2.7.1": {},
	"2.8":   {},
}

var AcknowledgementConditions = ControlTable{
	"AL": {},
	"ER": {},
	"NE": {},
	"SU": {},
}

var CountryCodes = ControlTable{
	"ABW": {}, "AFG": {}, "AGO": {}, "AIA": {}, "ALA": {}, "ALB": {}, "AND": {}, "ARE": {}, "ARG": {}, "ARM": {},
	"ASM": {}, "ATA": {}, "ATF": {}, "ATG": {}, "AUS": {}, "AUT": {}, "AZE": {}, "BDI": {}, "BEL": {}, "BEN": {},
	"BES": {}, "BFA": {}, "BGD": {}, "BGR": {}, "BHR": {}, "BHS": {}, "BIH": {}, "BLM": {}, "BLR": {}, "BLZ": {},
	"BMU": {}, "BOL": {}, "BRA": {}, "BRB": {}, "BRN": {}, "BTN": {}, "BVT": {}, "BWA": {}, "CAF": {}, "CAN": {},
	"CCK": {}, "CHE": {}, "CHL": {}, "CHN": {}, "CIV": {}, "CMR": {}, "COD": {}, "COG": {}, "COK": {}, "COL": {},
	"COM": {}, "CPV": {}, "CRI": {}, "CUB": {}, "CUW": {}, "CXR": {}, "CYM": {}, "CYP": {}, "CZE": {}, "DEU": {},
	"DJI": {}, "DMA": {}, "DNK": {}, "DOM": {}, "DZA": {}, "ECU": {}, "EGY": {}, "ERI": {}, "ESH": {}, "ESP": {},
	"EST": {}, "ETH": {}, "FIN": {}, "FJI": {}, "FLK": {}, "FRA": {}, "FRO": {}, "FSM": {}, "GAB": {}, "GBR": {},
	"GEO": {}, "GGY": {}, "GHA": {}, "GIB": {}, "GIN": {}, "GLP": {}, "GMB": {}, "GNB": {}, "GNQ": {}, "GRC": {},
	"GRD": {}, "GRL": {}, "GTM": {}, "GUF": {}, "GUM": {}, "GUY": {}, "HKG": {}, "HMD": {}, "HND": {}, "HRV": {},
	"HTI": {}, "HUN": {}, "IDN": {}, "IMN": {}, "IND": {}, "IOT": {}, "IRL": {}, "IRN": {}, "IRQ": {}, "ISL": {},
	"ISR": {}, "ITA": {}, "JAM": {}, "JEY": {}, "JOR": {}, "JPN": {}, "KAZ": {}, "KEN": {}, "KGZ": {}, "KHM": {},
	"KIR": {}, "KNA": {}, "KOR": {}, "KWT": {}, "LAO": {}, "LBN": {}, "LBR": {}, "LBY": {}, "LCA": {}, "LIE": {},
	"LKA": {}, "LSO": {}, "LTU": {}, "LUX": {}, "LVA": {}, "MAC": {}, "MAF": {}, "MAR": {}, "MCO": {}, "MDA": {},
	"MDG": {}, "MDV": {}, "MEX": {}, "MHL": {}, "MKD": {}, "MLI": {}, "MLT": {}, "MMR": {}, "MNE": {}, "MNG": {},
	"MNP": {}, "MOZ": {}, "MRT": {}, "MSR": {}, "MTQ": {}, "MUS": {}, "MWI": {}, "MYS": {}, "MYT": {}, "NAM": {},
	"NCL": {}, "NER": {}, "NFK": {}, "NGA": {}, "NIC": {}, "NIU": {}, "NLD": {}, "NOR": {}, "NPL": {}, "NRU": {},
	"NZL": {}, "OMN": {}, "PAK": {}, "PAN": {}, "PCN": {}, "PER": {}, "PHL": {}, "PLW": {}, "PNG": {}, "POL": {},
	"PRI": {}, "PRK": {}, "PRT": {}, "PRY": {}, "PSE": {}, "PYF": {}, "QAT": {}, "REU": {}, "ROU": {}, "RUS": {},
	"RWA": {}, "SAU": {}, "SDN": {}, "SEN": {}, "SGP": {}, "SGS": {}, "SHN": {}, "SJM": {}, "SLB": {}, "SLE": {},
	"SLV": {}, "SMR": {}, "SOM": {}, "SPM": {}, "SRB": {}, "SSD": {}, "STP": {}, "SUR": {}, "SVK": {}, "SVN": {},
	"SWE": {}, "SWZ": {}, "SXM": {}, "SYC": {}, "SYR": {}, "TCA": {}, "TCD": {}, "TGO": {}, "THA": {}, "TJK": {},
	"TKL": {}, "TKM": {}, "TLS": {}, "TON": {}, "TTO": {}, "TUN": {}, "TUR": {}, "TUV": {}, "TWN": {}, "TZA": {},
	"UGA": {}, "UKR": {}, "UMI": {}, "URY": {}, "USA": {}, "UZB": {}, "VAT": {}, "VCT": {}, "VEN": {}, "VGB": {},
	"VIR": {}, "VNM": {}, "VUT": {}, "WLF": {}, "WSM": {}, "YEM": {}, "ZAF": {}, "ZMB": {}, "ZWE": {},
}

// They're "alternate" because HL7 is supposed to be UTF-8
var AlternateCharacterSets = ControlTable{
	"8859/1":     {},
	"8859/2":     {},
	"8859/3":     {},
	"8859/4":     {},
	"8859/5":     {},
	"8859/6":     {},
	"8859/7":     {},
	"8859/8":     {},
	"8859/9":     {},
	"ASCII":      {},
	"JAS2020":    {},
	"JIS X 0202": {},
	"UNICODE":    {},
}

var IdentifierTypeCodes = ControlTable{
	"AM": {},
	"AN": {},
	"BR": {},
	"DI": {},
	"DL": {},
	"DS": {},
	"EI": {},
	"EN": {},
	"GI": {},
	"GN": {},
	"MA": {},
	"MC": {},
	"MR": {},
	"MS": {},
	"PI": {},
	"PT": {},
	"RR": {},
	"SS": {},
	"VN": {},
	"VS": {},
}

// NOTE: pretty much any of these tables that use ST/ID keys won't have a
// validator. Nobody in healthcare IT is sophisticated enough to use the
// following map, for example.
var ProcessingIds = map[ST]struct{}{
	"D": {},
	"P": {},
	"T": {},
}

var ProcessingModes = map[ST]struct{}{
	"a":           {},
	"i":           {},
	"Not present": {},
	"r":           {},
}

var CheckDigitScheme = map[ID]struct{}{
	"M10": {},
	"M11": {},
}

var NameTypeCodes = map[ID]struct{}{
	"A": {},
	"C": {},
	"D": {},
	"L": {},
	"M": {},
	"O": {},
}

var NameAddressRepresentation = map[ID]struct{}{
	"A": {},
	"I": {},
	"P": {},
}

var Sex = map[ID]struct{}{
	"F": {},
	"M": {},
	"O": {},
	"U": {},
}

var AddressTypes = map[ID]struct{}{
	"B": {},
	"C": {},
	"F": {},
	"H": {},
	"M": {},
	"O": {},
	"P": {},
}

// American, obviously
var States = map[ST]struct{}{
	"Alabama":        {},
	"Alaska":         {},
	"Arizona":        {},
	"Arkansas":       {},
	"California":     {},
	"Colorado":       {},
	"Connecticut":    {},
	"Delaware":       {},
	"Florida":        {},
	"Georgia":        {},
	"Hawaii":         {},
	"Idaho":          {},
	"Illinois":       {},
	"Indiana":        {},
	"Iowa":           {},
	"Kansas":         {},
	"Kentucky":       {},
	"Louisiana":      {},
	"Maine":          {},
	"Maryland":       {},
	"Massachusetts":  {},
	"Michigan":       {},
	"Minnesota":      {},
	"Mississippi":    {},
	"Missouri":       {},
	"Montana":        {},
	"Nebraska":       {},
	"Nevada":         {},
	"New Hampshire":  {},
	"New Jersey":     {},
	"New Mexico":     {},
	"New York":       {},
	"North Carolina": {},
	"North Dakota":   {},
	"Ohio":           {},
	"Oklahoma":       {},
	"Oregon":         {},
	"Pennsylvania":   {},
	"Rhode Island":   {},
	"South Carolina": {},
	"South Dakota":   {},
	"Tennessee":      {},
	"Texas":          {},
	"Utah":           {},
	"Vermont":        {},
	"Virginia":       {},
	"Washington":     {},
	"West Virginia":  {},
	"Wisconsin":      {},
	"Wyoming":        {},
}

var TelecommunicationUseCodes = map[ID]struct{}{
	"ASN": {},
	"BPN": {},
	"EMR": {},
	"NET": {},
	"ORN": {},
	"PRN": {},
	"VHN": {},
	"WPN": {},
}

var TelecommunicationEquipmentTypes = map[ID]struct{}{
	"BP":       {},
	"CP":       {},
	"FX":       {},
	"Internet": {},
	"MD":       {},
	"PH":       {},
	"X.400":    {},
}
