package faraday

// HL7- and ISO-defined tables.
// Note that this does not include user-defined tables.
// By nature, those should be configured.
var TableMap = map[string]*ControlTable{
	"0003":    &EventType,
	"0076":    &MessageType,
	"0061":    &CheckDigitScheme,
	"0102":    &RelationalConjunctions,
	"0103":    &ProcessingIds,
	"0104":    &VersionIds,
	"0155":    &AcknowledgementConditions,
	"0190":    &AddressTypes,
	"0191":    &ReferencedDataTypes,
	"0200":    &NameTypeCodes,
	"0201":    &TelecommunicationUseCodes,
	"0202":    &TelecommunicationEquipmentTypes,
	"0203":    &IdentifierTypeCodes,
	"0205":    &PriceTypes,
	"0207":    &ProcessingModes,
	"0209":    &RelationalOperators,
	"0211":    &AlternateCharacterSets,
	"0267":    &DaysOfWeek,
	"0291":    &ReferencedDataSubTypes,
	"0298":    &RangeTypes,
	"0301":    &UniversalIdTypes,
	"4000":    &NameRepresentationCodes,
	"ISO3166": &CountryCodes,
	"ISO4217": &IsoDenominations,
}

type ControlTable map[ID]string

func (table ControlTable) Valid(v ID) bool {
	_, ok := table[v]
	return ok
}

// HL7 Table 0003
var EventType = ControlTable{
	"022": "",
	"A01": "",
	"A02": "",
	"A03": "",
	"A04": "",
	"A05": "",
	"A06": "",
	"A07": "",
	"A08": "",
	"A09": "",
	"A10": "",
	"A11": "",
	"A12": "",
	"A13": "",
	"A14": "",
	"A15": "",
	"A16": "",
	"A17": "",
	"A18": "",
	"A19": "",
	"A20": "",
	"A21": "",
	"A22": "",
	"A23": "",
	"A24": "",
	"A25": "",
	"A26": "",
	"A27": "",
	"A28": "",
	"A29": "",
	"A30": "",
	"A31": "",
	"A32": "",
	"A33": "",
	"A34": "",
	"A35": "",
	"A36": "",
	"A37": "",
	"A38": "",
	"A39": "",
	"A40": "",
	"A41": "",
	"A42": "",
	"A43": "",
	"A44": "",
	"A45": "",
	"A46": "",
	"A47": "",
	"A48": "",
	"A49": "",
	"A50": "",
	"A51": "",
	"C01": "",
	"C02": "",
	"C03": "",
	"C04": "",
	"C05": "",
	"C06": "",
	"C07": "",
	"C08": "",
	"C09": "",
	"C10": "",
	"C11": "",
	"C12": "",
	"CNQ": "",
	"I01": "",
	"I02": "",
	"I03": "",
	"I04": "",
	"I05": "",
	"I06": "",
	"I07": "",
	"I08": "",
	"I09": "",
	"I10": "",
	"I11": "",
	"I12": "",
	"I13": "",
	"I14": "",
	"I15": "",
	"M01": "",
	"M02": "",
	"M03": "",
	"M04": "",
	"M05": "",
	"M06": "",
	"M07": "",
	"M08": "",
	"M09": "",
	"M10": "",
	"M11": "",
	"O01": "",
	"O02": "",
	"P01": "",
	"P02": "",
	"P03": "",
	"P04": "",
	"P05": "",
	"P06": "",
	"Q01": "",
	"Q02": "",
	"Q03": "",
	"Q04": "",
	"Q05": "",
	"Q06": "",
	"R01": "",
	"R02": "",
	"R03": "",
	"R04": "",
	"R05": "",
	"R06": "",
	"RAR": "",
	"RER": "",
	"ROR": "",
	"S01": "",
	"S02": "",
	"S03": "",
	"S04": "",
	"S05": "",
	"S06": "",
	"S07": "",
	"S08": "",
	"S09": "",
	"S10": "",
	"S11": "",
	"S12": "",
	"S13": "",
	"S14": "",
	"S15": "",
	"S16": "",
	"S17": "",
	"S18": "",
	"S19": "",
	"S20": "",
	"S21": "",
	"S22": "",
	"S23": "",
	"S24": "",
	"S25": "",
	"S26": "",
	"T01": "",
	"T02": "",
	"T03": "",
	"T04": "",
	"T05": "",
	"T06": "",
	"T07": "",
	"T09": "",
	"V01": "",
	"V02": "",
	"V03": "",
	"V04": "",
	"W01": "",
	"W02": "",
}

// HL7 Table 0061
var CheckDigitScheme = ControlTable{
	"M10": "",
	"M11": "",
}

// HL7 Table 0076
var MessageType = ControlTable{
	"ACK": "",
	"ADR": "",
	"ADT": "",
	"ARD": "",
	"BAR": "",
	"CNQ": "",
	"CSU": "",
	"DFT": "",
	"DSR": "",
	"EDR": "",
	"ERP": "",
	"EQQ": "",
	"MCF": "",
	"MDM": "",
	"MFD": "",
	"MFK": "",
	"MFN": "",
	"MFQ": "",
	"MFR": "",
	"ORF": "",
	"ORM": "",
	"ORR": "",
	"ORU": "",
	"OSQ": "",
	"OSR": "",
	"PEX": "",
	"PGL": "",
	"PGQ": "",
	"PPG": "",
	"PPP": "",
	"PPR": "",
	"PPT": "",
	"PPV": "",
	"PRR": "",
	"PTR": "",
	"PTV": "",
	"QRY": "",
	"RAR": "",
	"RAS": "",
	"RCI": "",
	"RCL": "",
	"RDE": "",
	"RDR": "",
	"RDS": "",
	"REF": "",
	"RER": "",
	"RGR": "",
	"RGV": "",
	"ROC": "",
	"ROD": "",
	"ROR": "",
	"RPA": "",
	"RPI": "",
	"RPL": "",
	"RPR": "",
	"RQA": "",
	"RQC": "",
	"RQI": "",
	"RRA": "",
	"RRD": "",
	"RRE": "",
	"RRG": "",
	"RRI": "",
	"SIU": "",
	"SPQ": "",
	"SQM": "",
	"SQR": "",
	"SRM": "",
	"SRR": "",
	"SUR": "",
	"TBR": "",
	"UDM": "",
	"VQQ": "",
	"VXQ": "",
	"VXR": "",
	"VXU": "",
	"VXX": "",
}

// HL7 Table 0102
var RelationalConjunctions = ControlTable{
	"AND": "",
	"OR":  "",
}

// HL7 Table 0103
var ProcessingIds = ControlTable{
	"D": "",
	"P": "",
	"T": "",
}

// HL7 Table 0104
var VersionIds = ControlTable{
	"2.0":   "",
	"2.0D":  "",
	"2.1":   "",
	"2.2":   "",
	"2.3":   "",
	"2.3.1": "",
	"2.4":   "",
	"2.5":   "",
	"2.6":   "",
	"2.7":   "",
	"2.7.1": "",
	"2.8":   "",
}

// HL7 Table 0155
var AcknowledgementConditions = ControlTable{
	"AL": "Always",
	"ER": "Error conditions only",
	"NE": "Never",
	"SU": "Successful completion only",
}

// HL7 Table 0190
var AddressTypes = ControlTable{
	"B": "", // Firm/Business
	"C": "", // Current or Temporary
	"F": "", // Country of Origin
	"H": "", // Home
	"M": "", // Mailing
	"N": "", // Birth (nee)
	"O": "", // Office
	"P": "", // Permanent
}

// HL7 Table 0191
var ReferencedDataTypes = ControlTable{
	"SI":          "scanned image",
	"NS":          "non-scanned image",
	"SD":          "scanned document",
	"TX":          "machine readable text document",
	"FT":          "formatted text",
	"Image":       "image data",
	"Audio":       "audio data",
	"Application": "other application data (binary)",
}

// HL7 Table 0200
var NameTypeCodes = ControlTable{
	"A": "",
	"C": "",
	"D": "",
	"L": "",
	"M": "",
}

// HL7 Table 0201
var TelecommunicationUseCodes = ControlTable{
	"ASN": "Answering service number",
	"BPN": "Beeper number",
	"EMR": "Emergency number",
	"NET": "Network email address",
	"ORN": "Other residence number",
	"PRN": "Primary residence number",
	"VHN": "Vacation home number",
	"WPN": "Work number",
}

// HL7 Table 0202
var TelecommunicationEquipmentTypes = ControlTable{
	"BP":       "Beeper",
	"CP":       "Cellphone",
	"FX":       "Fax",
	"Internet": "Internet",
	"MD":       "Modem",
	"PH":       "Telephone",
	"X.400":    "X.400 email address",
}

// HL7 Table 0203
var IdentifierTypeCodes = ControlTable{
	"AM":   "American Express",
	"AN":   "Account Number",
	"BR":   "Birth Registry Number",
	"DI":   "Diner's Club Card",
	"DL":   "Driver's License Number",
	"DN":   "Doctor Number",
	"DS":   "Discover Card",
	"EI":   "Employee Number",
	"EN":   "Employer Number",
	"GI":   "Guarantor Internal Identifier",
	"GN":   "Guarantor External Identifier",
	"MA":   "Medicaid Number",
	"MC":   "Medicare Number",
	"MR":   "Medicaid Record Number",
	"MS":   "MasterCard",
	"PI":   "Patient Internal Identifier",
	"PN":   "Person Number",
	"PT":   "Patient External Identifier",
	"RR":   "Railroad Retirement Number",
	"SS":   "Social Security Number",
	"UPIN": "Medicare/HCFA's Universal Physician Identification Numbers",
	"VN":   "Visit Number",
	"VS":   "VISA",
	"XX":   "Organization Identifier",
}

// HL7 Table 0205
var PriceTypes = ControlTable{
	"AP": "administrative price or handling fee",
	"PF": "professional fee for performing provider",
	"UP": "unit price, may be based on length of procedure or service",
	"TF": "technology fee for use of equipment",
	"DC": "direct unit cost",
	"IC": "indirect unit cost",
	"TP": "total price",
}

// HL7 Table 0207
var ProcessingModes = ControlTable{
	"a":           "",
	"i":           "",
	"Not present": "",
	"r":           "",
}

// HL7 Table 0209
var RelationalOperators = ControlTable{
	"EQ": "Equal",
	"NE": "Not Equal",
	"LT": "Less than",
	"GT": "Greater than",
	"LE": "Less than or equal",
	"GE": "Greater than or equal",
	"CT": "Contains",
	"GN": "Generic",
}

// HL7 Table 0211
var AlternateCharacterSets = ControlTable{
	"8859/1":          "ISO 8859/1",
	"8859/2":          "ISO 8859/2",
	"8859/3":          "ISO 8859/3",
	"8859/4":          "ISO 8859/4",
	"8859/5":          "ISO 8859/5",
	"8859/6":          "ISO 8859/6",
	"8859/7":          "ISO 8859/7",
	"8859/8":          "ISO 8859/8",
	"8859/9":          "ISO 8859/9",
	"ASCII":           "default ASCII",
	"JAS2020":         "Japanese Kanji",
	"JIS X 0202":      "ISO 2022 for Kanji",
	"JIS X 0201-1976": "Code for Information Exchange",
	"JIS X 0208-1990": "Japanese Graphic Character set",
	"JIS X 0212-1990": "Japanese Graphic Character set, supplementary",
}

// HL7 Table 0267
var DaysOfWeek = ControlTable{
	"SAT": "Saturday",
	"SUN": "Sunday",
	"MON": "Monday",
	"TUE": "Tuesday",
	"WED": "Wednesday",
	"THU": "Thursday",
	"FRI": "Friday",
}

// HL7 Table 0291
var ReferencedDataSubTypes = ControlTable{
	"TIFF":         "TIFF image data",
	"PICT":         "PICT image data",
	"DICOM":        "Digital Imaging and Communications in Medicine",
	"FAX":          "facsimile data",
	"JOT":          "electronic ink data",
	"BASIC":        "ISDN PCM audio data",
	"Octet-stream": "Uninterpreted binary data",
	"PostScript":   "PostScript program",
	"JPEG":         "joint photographic experts group",
	"GIF":          "graphics interchange format",
	"HTML":         "hypertext markup language",
	"RTF":          "rich text format",
}

// HL7 Table 0298
var RangeTypes = ControlTable{
	"P": "pro-rate",
	"F": "flat-rate",
}

// HL7 Table 0301
var UniversalIdTypes = ControlTable{
	"DNS":    "Internet dotted name (ASCII or integers)",
	"GUID":   "alias for UUID",
	"HCD":    "CEN Healthcare Coding Scheme Designator",
	"HL7":    "HL7 registration scheme",
	"ISO":    "International Standards Organization",
	"L":      "Locally Defined",
	"M":      "Locally Defined",
	"N":      "Locally Defined",
	"Random": "random bits",
	"UUID":   "Universal Unique Identifier",
	"x400":   "X.400 MHS format identifier",
	"x500":   "X.500 directory name",
}

// HL7 Table 4000
var NameRepresentationCodes = ControlTable{
	"I": "Ideographic",
	"A": "Alphabetic",
	"P": "Phonetic",
}

// ISO 3166
var CountryCodes = ControlTable{
	"ABW": "", "AFG": "", "AGO": "", "AIA": "", "ALA": "", "ALB": "", "AND": "", "ARE": "", "ARG": "", "ARM": "",
	"ASM": "", "ATA": "", "ATF": "", "ATG": "", "AUS": "", "AUT": "", "AZE": "", "BDI": "", "BEL": "", "BEN": "",
	"BES": "", "BFA": "", "BGD": "", "BGR": "", "BHR": "", "BHS": "", "BIH": "", "BLM": "", "BLR": "", "BLZ": "",
	"BMU": "", "BOL": "", "BRA": "", "BRB": "", "BRN": "", "BTN": "", "BVT": "", "BWA": "", "CAF": "", "CAN": "",
	"CCK": "", "CHE": "", "CHL": "", "CHN": "", "CIV": "", "CMR": "", "COD": "", "COG": "", "COK": "", "COL": "",
	"COM": "", "CPV": "", "CRI": "", "CUB": "", "CUW": "", "CXR": "", "CYM": "", "CYP": "", "CZE": "", "DEU": "",
	"DJI": "", "DMA": "", "DNK": "", "DOM": "", "DZA": "", "ECU": "", "EGY": "", "ERI": "", "ESH": "", "ESP": "",
	"EST": "", "ETH": "", "FIN": "", "FJI": "", "FLK": "", "FRA": "", "FRO": "", "FSM": "", "GAB": "", "GBR": "",
	"GEO": "", "GGY": "", "GHA": "", "GIB": "", "GIN": "", "GLP": "", "GMB": "", "GNB": "", "GNQ": "", "GRC": "",
	"GRD": "", "GRL": "", "GTM": "", "GUF": "", "GUM": "", "GUY": "", "HKG": "", "HMD": "", "HND": "", "HRV": "",
	"HTI": "", "HUN": "", "IDN": "", "IMN": "", "IND": "", "IOT": "", "IRL": "", "IRN": "", "IRQ": "", "ISL": "",
	"ISR": "", "ITA": "", "JAM": "", "JEY": "", "JOR": "", "JPN": "", "KAZ": "", "KEN": "", "KGZ": "", "KHM": "",
	"KIR": "", "KNA": "", "KOR": "", "KWT": "", "LAO": "", "LBN": "", "LBR": "", "LBY": "", "LCA": "", "LIE": "",
	"LKA": "", "LSO": "", "LTU": "", "LUX": "", "LVA": "", "MAC": "", "MAF": "", "MAR": "", "MCO": "", "MDA": "",
	"MDG": "", "MDV": "", "MEX": "", "MHL": "", "MKD": "", "MLI": "", "MLT": "", "MMR": "", "MNE": "", "MNG": "",
	"MNP": "", "MOZ": "", "MRT": "", "MSR": "", "MTQ": "", "MUS": "", "MWI": "", "MYS": "", "MYT": "", "NAM": "",
	"NCL": "", "NER": "", "NFK": "", "NGA": "", "NIC": "", "NIU": "", "NLD": "", "NOR": "", "NPL": "", "NRU": "",
	"NZL": "", "OMN": "", "PAK": "", "PAN": "", "PCN": "", "PER": "", "PHL": "", "PLW": "", "PNG": "", "POL": "",
	"PRI": "", "PRK": "", "PRT": "", "PRY": "", "PSE": "", "PYF": "", "QAT": "", "REU": "", "ROU": "", "RUS": "",
	"RWA": "", "SAU": "", "SDN": "", "SEN": "", "SGP": "", "SGS": "", "SHN": "", "SJM": "", "SLB": "", "SLE": "",
	"SLV": "", "SMR": "", "SOM": "", "SPM": "", "SRB": "", "SSD": "", "STP": "", "SUR": "", "SVK": "", "SVN": "",
	"SWE": "", "SWZ": "", "SXM": "", "SYC": "", "SYR": "", "TCA": "", "TCD": "", "TGO": "", "THA": "", "TJK": "",
	"TKL": "", "TKM": "", "TLS": "", "TON": "", "TTO": "", "TUN": "", "TUR": "", "TUV": "", "TWN": "", "TZA": "",
	"UGA": "", "UKR": "", "UMI": "", "URY": "", "USA": "", "UZB": "", "VAT": "", "VCT": "", "VEN": "", "VGB": "",
	"VIR": "", "VNM": "", "VUT": "", "WLF": "", "WSM": "", "YEM": "", "ZAF": "", "ZMB": "", "ZWE": "",
}

// ISO 4217 Table A.1
var IsoDenominations = ControlTable{
	"AED": "United Arab Emirates dirham",
	"AFN": "Afghan afghani",
	"ALL": "Albanian lek",
	"AMD": "Armenian dram",
	"AOA": "Angolan kwanza",
	"ARS": "Argentine peso",
	"AUD": "Australian dollar",
	"AWG": "Aruban florin",
	"AZN": "Azerbaijani manat",
	"BAM": "Bosnia and Herzegovina convertible mark",
	"BBD": "Barbados dollar",
	"BDT": "Bangladeshi taka",
	"BGN": "Bulgarian lev",
	"BHD": "Bahraini dinar",
	"BIF": "Burundian franc",
	"BMD": "Bermudian dollar",
	"BND": "Brunei dollar",
	"BOB": "Boliviano",
	"BOV": "Bolivian Mvdol (funds code)",
	"BRL": "Brazilian real",
	"BSD": "Bahamian dollar",
	"BTN": "Bhutanese ngultrum",
	"BWP": "Botswana pula",
	"BYN": "Belarusian ruble",
	"BZD": "Belize dollar",
	"CAD": "Canadian dollar",
	"CDF": "Congolese franc",
	"CHE": "WIR euro (complementary currency)",
	"CHF": "Swiss franc",
	"CHW": "WIR franc (complementary currency)",
	"CLF": "Unidad de Fomento (funds code)",
	"CLP": "Chilean peso",
	"CNY": "Renminbi",
	"COP": "Colombian peso",
	"COU": "Unidad de Valor Real (UVR) (funds code)",
	"CRC": "Costa Rican colon",
	"CUP": "Cuban peso",
	"CVE": "Cape Verdean escudo",
	"CZK": "Czech koruna",
	"DJF": "Djiboutian franc",
	"DKK": "Danish krone",
	"DOP": "Dominican peso",
	"DZD": "Algerian dinar",
	"EGP": "Egyptian pound",
	"ERN": "Eritrean nakfa",
	"ETB": "Ethiopian birr",
	"EUR": "Euro",
	"FJD": "Fiji dollar",
	"FKP": "Falkland Islands pound",
	"GBP": "Pound sterling",
	"GEL": "Georgian lari",
	"GHS": "Ghanaian cedi",
	"GIP": "Gibraltar pound",
	"GMD": "Gambian dalasi",
	"GNF": "Guinean franc",
	"GTQ": "Guatemalan quetzal",
	"GYD": "Guyanese dollar",
	"HKD": "Hong Kong dollar",
	"HNL": "Honduran lempira",
	"HTG": "Haitian gourde",
	"HUF": "Hungarian forint",
	"IDR": "Indonesian rupiah",
	"ILS": "Israeli new shekel",
	"INR": "Indian rupee",
	"IQD": "Iraqi dinar",
	"IRR": "Iranian rial",
	"ISK": "Icelandic króna",
	"JMD": "Jamaican dollar",
	"JOD": "Jordanian dinar",
	"JPY": "Japanese yen",
	"KES": "Kenyan shilling",
	"KGS": "Kyrgyzstani som",
	"KHR": "Cambodian riel",
	"KMF": "Comoro franc",
	"KPW": "North Korean won",
	"KRW": "South Korean won",
	"KWD": "Kuwaiti dinar",
	"KYD": "Cayman Islands dollar",
	"KZT": "Kazakhstani tenge",
	"LAK": "Lao kip",
	"LBP": "Lebanese pound",
	"LKR": "Sri Lankan rupee",
	"LRD": "Liberian dollar",
	"LSL": "Lesotho loti",
	"LYD": "Libyan dinar",
	"MAD": "Moroccan dirham",
	"MDL": "Moldovan leu",
	"MGA": "Malagasy ariary",
	"MKD": "Macedonian denar",
	"MMK": "Myanmar kyat",
	"MNT": "Mongolian tögrög",
	"MOP": "Macanese pataca",
	"MRU": "Mauritanian ouguiya",
	"MUR": "Mauritian rupee",
	"MVR": "Maldivian rufiyaa",
	"MWK": "Malawian kwacha",
	"MXN": "Mexican peso",
	"MXV": "Mexican Unidad de Inversion (UDI) (funds code)",
	"MYR": "Malaysian ringgit",
	"MZN": "Mozambican metical",
	"NAD": "Namibian dollar",
	"NGN": "Nigerian naira",
	"NIO": "Nicaraguan córdoba",
	"NOK": "Norwegian krone",
	"NPR": "Nepalese rupee",
	"NZD": "New Zealand dollar",
	"OMR": "Omani rial",
	"PAB": "Panamanian balboa",
	"PEN": "Peruvian sol",
	"PGK": "Papua New Guinean kina",
	"PHP": "Philippine peso",
	"PKR": "Pakistani rupee",
	"PLN": "Polish złoty",
	"PYG": "Paraguayan guaraní",
	"QAR": "Qatari riyal",
	"RON": "Romanian leu",
	"RSD": "Serbian dinar",
	"RUB": "Russian ruble",
	"RWF": "Rwandan franc",
	"SAR": "Saudi riyal",
	"SBD": "Solomon Islands dollar",
	"SCR": "Seychelles rupee",
	"SDG": "Sudanese pound",
	"SEK": "Swedish krona",
	"SGD": "Singapore dollar",
	"SHP": "Saint Helena pound",
	"SLE": "Sierra Leonean leone",
	"SOS": "Somalian shilling",
	"SRD": "Surinamese dollar",
	"SSP": "South Sudanese pound",
	"STN": "São Tomé and Príncipe dobra",
	"SVC": "Salvadoran colón",
	"SYP": "Syrian pound",
	"SZL": "Swazi lilangeni",
	"THB": "Thai baht",
	"TJS": "Tajikistani somoni",
	"TMT": "Turkmenistan manat",
	"TND": "Tunisian dinar",
	"TOP": "Tongan paʻanga",
	"TRY": "Turkish lira",
	"TTD": "Trinidad and Tobago dollar",
	"TWD": "New Taiwan dollar",
	"TZS": "Tanzanian shilling",
	"UAH": "Ukrainian hryvnia",
	"UGX": "Ugandan shilling",
	"USD": "United States dollar",
	"USN": "United States dollar (next day)",
	"UYI": "Uruguay Peso en Unidades Indexadas (URUIURUI)",
	"UYU": "Uruguayan peso",
	"UYW": "Unidad previsional",
	"UZS": "Uzbekistani sum",
	"VED": "Venezuelan digital bolívar",
	"VES": "Venezuelan sovereign bolívar",
	"VND": "Vietnamese đồng",
	"VUV": "Vanuatu vatu",
	"WST": "Samoan tala",
	"XAD": "Arab Accounting Dinar",
	"XAF": "CFA franc BEAC",
	"XAG": "Silver (one troy ounce)",
	"XAU": "Gold (one troy ounce)",
	"XBA": "European Composite Unit (EURCO)",
	"XBB": "European Monetary Unit (E.M.U.-6)",
	"XBC": "European Unit of Account 9 (E.U.A.-9)",
	"XBD": "European Unit of Account 17 (E.U.A.-17)",
	"XCD": "East Caribbean dollar",
	"XCG": "Caribbean guilder",
	"XDR": "Special drawing rights",
	"XOF": "CFA franc BCEAO",
	"XPD": "Palladium (one troy ounce)",
	"XPF": "CFP franc (franc Pacifique)",
	"XPT": "Platinum (one troy ounce)",
	"XSU": "SUCRE",
	"XTS": "Code reserved for testing",
	"XUA": "ADB Unit of Account",
	"XXX": "No currency",
	"YER": "Yemeni rial",
	"ZAR": "South African rand",
	"ZMW": "Zambian kwacha",
	"ZWG": "Zimbabwe Gold",
}

var SegmentTypes = map[string]struct{}{
	"ACC": {},
	"ADD": {},
	"AID": {},
	"AIL": {},
	"AIP": {},
	"AIS": {},
	"AL1": {},
	"APR": {},
	"ARQ": {},
	"AUT": {},
	"BHS": {},
	"BLG": {},
	"BS":  {},
	"CDM": {},
	"CM0": {},
	"CM1": {},
	"CM2": {},
	"CSP": {},
	"CSR": {},
	"CSS": {},
	"CTD": {},
	"CTI": {},
	"DG1": {},
	"DRG": {},
	"DSC": {},
	"DSP": {},
	"EQL": {},
	"ERQ": {},
	"ERR": {},
	"EVN": {},
	"FAC": {},
	"FHS": {},
	"FT1": {},
	"FTS": {},
	"GT1": {},
	"IN1": {},
	"IN2": {},
	"IN3": {},
	"LCC": {},
	"LCH": {},
	"LDP": {},
	"LOC": {},
	"LRL": {},
	"MFA": {},
	"MFE": {},
	"MFI": {},
	"MRG": {},
	"MSA": {},
	"MSH": {},
	"NK1": {},
	"NPU": {},
	"NTE": {},
	"OBR": {},
	"OBX": {},
	"ODS": {},
	"ODT": {},
	"OM1": {},
	"OM2": {},
	"OM3": {},
	"OM4": {},
	"OM5": {},
	"OM6": {},
	"ORC": {},
	"PCR": {},
	"PD1": {},
	"PDC": {},
	"PEO": {},
	"PES": {},
	"PID": {},
	"PR1": {},
	"PRA": {},
	"PRC": {},
	"PRD": {},
	"PSR": {},
	"PV1": {},
	"PV2": {},
	"QAK": {},
	"QRD": {},
	"QRF": {},
	"RDF": {},
	"RDT": {},
	"RF1": {},
	"RQ1": {},
	"RQD": {},
	"RXA": {},
	"RXC": {},
	"RXD": {},
	"RXE": {},
	"RXG": {},
	"RXO": {},
	"RXR": {},
	"SCH": {},
	"STF": {},
	"SPR": {},
	"TXA": {},
	"UB1": {},
	"UB2": {},
	"URD": {},
	"URS": {},
	"VTQ": {},
}
